# Copyright 2025 Cockroach Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release build
on:
  release:
    types:
      - created
jobs:
  build:
    uses: ./.github/workflows/go-build.yaml
  upload-binaries:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    strategy:
      matrix:
        include:
          - platform: linux-amd64
          - platform: linux-arm64
          - platform: darwin-arm64
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: blobcheck-${{ matrix.platform }}
      - name: Upload binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ github.event.release.tag_name }}
          mv "blobcheck-${{ matrix.platform }}" "blobcheck-${TAG}-${{ matrix.platform }}"
          gh -R ${{ github.repository }} release upload "${TAG}" "blobcheck-${TAG}-${{ matrix.platform }}"
